package gestion;

public enum lineasEnfasis {
	SUELOS,SANIDADVEGETAL,FISIOLOGIAVEGETAYBIOTECNOLOGIA,FITOMEJORAMIENTO,
	PRODUCCIONDESARROLLORURAL,RIEGOYDRENAJE,MECANIZACIONAGRICOLA,PROCESOSAGROINDUSTRIALES
	,AMBIENTERURAL,TECNICASAGRICOLAS;
}
