package gestion;

public enum LineasEnfasis {
	SUELOS, SANIDADVEGETAL, FISIOLOGIAVEGETAYBIOTECNOLOGIA, FITOMEJORAMIENTO,
	PRODUCCIONDESARROLLORURAL, RIEGOYDRENAJE,MECANIZACIONAGRICOLA, PROCESOSAGROINDUSTRIALES
	, AMBIENTERURAL, TECNICASAGRICOLAS, IA, SITEMAS, INGENIERISOFTWARE, ANALISISDATOS, REDES;
}
