package gestorAplicacion.gestion;

public enum LineasEnfasis {
	SUELOS, SANIDADVEGETAL, FISIOLOGIAVEGETAYBIOTECNOLOGIA, FITOMEJORAMIENTO,
	PRODUCCIONDESARROLLORURAL, RIEGOYDRENAJE,MECANIZACIONAGRICOLA, PROCESOSAGROINDUSTRIALES
	, AMBIENTERURAL, TECNICASAGRICOLAS, IA, SISTEMAS, INGENIERISOFTWARE, ANALISISDATOS, REDES;
}
